loadbalancing:
  middleware: {
    name: "middleware",
    port: 401,
    heartbeat: { url: "/", method: "GET" },
    hostgroup: "app",
  }

# Format: PEM RSA PRIVATE KEY
nginx_gateway_key: "{{ lookup('file', inventory_dir+'/ssl_cert/gateway.key') }}"

# Format: PEM RSA PRIVATE KEY
nginx_selfservice_key: "{{ lookup('file', inventory_dir+'/ssl_cert/selfservice.key') }}"

# Format: PEM RSA PRIVATE KEY
nginx_ra_key: "{{ lookup('file', inventory_dir+'/ssl_cert/ra.key') }}"


# Format: PEM Certificate (chain)
# Order: SSL Server certificate followed by intermediate certificate(s) in chain order.
# Do not include root CA certificate
nginx_gateway_certificate: "{{ lookup('file', inventory_dir+'/ssl_cert/gateway.crt') }}"

# Format: PEM Certificate (chain)
# Order: SSL Server certificate followed by intermediate certificate(s) in chain order.
# Do not include root CA certificate
nginx_selfservice_certificate: "{{ lookup('file', inventory_dir+'/ssl_cert/selfservice.crt') }}"

# Format: PEM Certificate (chain)
# Order: SSL Server certificate followed by intermediate certificate(s) in chain order.
# Do not include root CA certificate
nginx_ra_certificate: "{{ lookup('file', inventory_dir+'/ssl_cert/ra.crt') }}"
