# Configuration for middleware component

# Used for Symfony CSRF protection
middleware_secret: "{{ lookup('file', inventory_dir+'/secret/middleware') }}"

# List of users (identities) that have Super RA Administrators rights
# The nameid's in the list below are used in "../templates/middleware/middleware-config.json.j2"
# To add/remove SRAA's add/remove them to the list below and then push a new middleware configuration.
# For more information see: "../templates/middleware/middleware-config.json.j2"
#
# The information beyond nameid is *only* used by the middleware bootstrap script on the app server:
# /root/06-middleware-bootstrap-sraa-users.sh
# To update this boostrap script file after making changes here, redeploy the Stepup-Middleware component

# TODO: Define SRAA's
middleware_sraa:
    - { nameid: "urn:collab:person:pieter.aai.surfnet.nl:pieter", institution: pieter.aai.surfnet.nl, cn: "Pieter van der Meulen", email: pieter.vandermeulen@surfnet.nl, lang: nl_NL, yubikey_id: 01906374 }
    - { nameid: "urn:collab:person:pieter.aai.surfnet.nl:joost", institution: pieter.aai.surfnet.nl, cn: "Joost van Dijk", email: joost.vandijk@surfnet.nl, lang: nl_NL, yubikey_id: 01960573 }
