---
- name: Remove the old mariadb-libs
  become: yes
  yum: pkg=mariadb-libs state=absent

- name: Add MariaDB.org repository
  become: yes
  template: src='mariadb.repo.j2' dest='/etc/yum.repos.d/mariadb.repo'

- name: Add the MariaDB key
  become: yes
  command: rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

- name: Install MariaDB
  become: yes
  yum: pkg={{item}} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-shared
    - MySQL-python

- name: Change MariaDB bind address 0.0.0.0
  lineinfile: dest=/etc/my.cnf.d/server.cnf regexp="^bind-address = " insertafter="^\[mysqld\]" line="bind-address = 0.0.0.0"
  notify: Restart MariaDB

- name: Start MariaDB
  become: true
  service: name=mysql enabled=yes state=started

- name: Set root password
  shell: mysqladmin -uroot password {{ mariadb_root_password|quote }} && touch /home/vagrant/.mariadb_root_password_set creates=/home/vagrant/.mariadb_root_password_set

- name: Add Middleware database
  mysql_db: name=middleware state=present login_user=root login_password={{ mariadb_root_password }}

- name: Add Gateway database
  mysql_db: name=gateway state=present login_user=root login_password={{ mariadb_root_password }}

- name: Add U2F database
  mysql_db: name=u2f state=present login_user=root login_password={{ mariadb_root_password }}

- name: Grant middleware access to database middleware
  mysql_user: host=% name=middleware password=middleware priv=middleware.*:DELETE,INSERT,SELECT,UPDATE,EXECUTE login_user=root login_password={{ mariadb_root_password }}

- name: Grant gateway access to database gateway
  mysql_user: host=% name=gateway password=gateway priv=gateway.*:SELECT,EXECUTE login_user=root login_password={{ mariadb_root_password }}

- name: Grant u2f access to database u2f
  mysql_user: host=% name=u2f password=u2f priv=u2f.*:DELETE,INSERT,SELECT,UPDATE,EXECUTE login_user=root login_password={{ mariadb_root_password }}

- name: Grant deploy user access to middleware, gateway, u2f databases
  mysql_user: host=% name=deploy password=deploy priv=middleware.*:ALL,GRANT/gateway.*:ALL,GRANT/u2f.*:ALL,GRANT login_user=root login_password={{ mariadb_root_password }}

- name: Add firewall rule for MariaDB
  become: yes
  firewalld: service=mysql permanent=true state=enabled
  notify: Reload firewall
