- name: Install haproxy
  yum: name=haproxy.x86_64 state=present

- name: Install socat
  yum: name=socat state=present

- name: Enable haproxy
  service: name=haproxy enabled=yes
  notify:
    - restart haproxy

- debug: var=loadbalancing

- name: Copy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: reload haproxy

- name: Start haproxy
  service: name=haproxy state=started

