---
- name: Install certificate for {{ component_name }}
  copy: content="{{ vhost_certificate }}" dest=/etc/nginx/keys/{{ vhost_name }}.crt
  notify:
      - restart nginx

- name: Install key for {{ component_name }}
  copy: content="{{ vhost_key | vault(vault_keydir) }}" dest=/etc/nginx/keys/{{ vhost_name }}.key owner=root mode=400
  notify:
      - restart nginx

- name: Install vhost.conf for {{ vhost_name }}
  template: src='nginx.vhost.conf.j2' dest='/etc/nginx/conf.d/{{ vhost_name }}.conf'
  notify:
      - restart nginx

