---

- name: Install nginx
  yum: name={{item}} state=present
  with_items:
  - nginx


# Remove default distro conf files
- name: Remove conf.d/welcome.conf
  file: path={{item}} state=absent
  with_items:
  - /etc/nginx/conf.d/default.conf
  - /etc/nginx/conf.d/ssl.conf
  - /etc/nginx/conf.d/virtual.conf
  notify:
  - restart nginx


- name: Put manage nginx.conf
  template: src='nginx-https/nginx.conf.j2' dest='/etc/nginx/nginx.conf'
  notify:
      - restart nginx

- name: Put manage.conf
  template: src='nginx-https/manage.conf.j2' dest='/etc/nginx/conf.d/manage.conf'
  notify:
      - restart nginx


- name: Put manage cert
  copy: content="{{ manage_certificiate }}" dest=/etc/nginx/manage.crt
  notify:
      - restart nginx

- name: Put manage key
  copy: content="{{ manage_key | vault(vault_keydir) }}" dest=/etc/nginx/manage.key owner=root mode=400
  notify:
      - restart nginx

- name: Start and enable nginx
  service: name=nginx state=started enabled=yes
