---

# To deploy all components in one go, set "tarball_location" to the directory where the tarballls to be deployed are stored. E.g.
# ansible-playbook .../Stepup-Deploy/deploy.yml -i .../inventory -e tarball_location=`pwd`
#
# Use the provided deploy.sh script to deploy a single component


- name: Intall Stepup-Gateway
  hosts: stepup-gateway
  sudo: True
  tags: stepup-gateway

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-Gateway-1.0.0-20150619132459Z-19765431f0f30ded4bf7732dd0caa3a4ff6a9def.tar.bz2"
      component_name: gateway
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"

  roles:
      - stepup-gateway


- name: Install Stepup-middleware
  hosts: stepup-middleware
  sudo: True
  tags: stepup-middleware

  roles:
        - stepup-middleware

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-Middleware-1.0.0-20150619132803Z-92f3383bc292a3a906b6587ecb52d0b1cfdd0950.tar.bz2"
      component_name: middleware
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-SelfService
  hosts: stepup-selfservice
  sudo: True
  tags: stepup-selfservice

  roles:
        - stepup-selfservice

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-SelfService-1.0.0-20150619132749Z-4c8e8d1ad209603791855a114d7843d4bc74aab4.tar.bz2"
      component_name: selfservice
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-RA
  hosts: stepup-ra
  sudo: True
  tags: stepup-ra

  roles:
        - stepup-ra

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-RA-1.0.0-20150619132450Z-49bef3fe7b2759c78a66636d8b2d559f162363d6.tar.bz2"
      component_name: ra
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-tiqr IDP
  hosts: stepup-tiqr
  sudo: True
  tags: stepup-tiqr

  roles:
        - stepup-tiqr

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-tiqr-1.0.0-20150619100355Z-53107ae04169d8535a5fe45c335d30ea4800337f.tar.bz2"
      component_name: tiqr
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-Keyserver
  hosts: stepup-keyserver
  sudo: True
  tags: oath-service-php

  roles:
        - stepup-keyserver

  vars:
      component_tarball_name: "{{ tarball_location }}/oath-service-php-1.0.0-20150612142526Z-b818c2463a68e874d0ab1cbeac3197cf92901996.tar.bz2"
      component_name: keyserver
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"
