- name: Intall Stepup-Gateway
  hosts: stepup-gateway
  sudo: True
  tags: stepup-gateway

  vars:
      component_tarball_name: Stepup-Gateway-develop-20141202081514Z-e8ef9e8b0a34180c14fefbe3a847edc47c3ef3be.tar.bz2
      component_name: gateway
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"

  roles:
      - stepup-gateway


- name: Install Stepup-middleware
  hosts: stepup-middleware
  sudo: True
  tags: stepup-middleware

  roles:
        - stepup-middleware

  vars:
      component_tarball_name: Stepup-Middleware-bugfix_api-entity-metadata-20141210091501Z-84dd3a1ff54672d9d8a3e926a8901bdc41a00dae.tar.bz2
      component_name: middleware
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-SelfService
  hosts: stepup-selfservice
  sudo: True
  tags: stepup-selfservice

  roles:
        - stepup-selfservice

  vars:
      component_tarball_name: Stepup-SelfService-develop-20141210133202Z-716d9a0c78ad65f5160d7572abae673c156faf36.tar.bz2
      component_name: selfservice
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-RA
  hosts: stepup-ra
  sudo: True
  tags: stepup-ra

  roles:
        - stepup-ra

  vars:
      component_tarball_name: Stepup-RA-develop-20141210133225Z-9c5949d14b7abbcccddcd4c46c1fe42d82690f18.tar.bz2
      component_name: ra
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-tiqr IDP
  hosts: stepup-tiqr
  sudo: True
  tags: stepup-tiqr

  roles:
        - stepup-tiqr

  vars:
      component_tarball_name: Stepup-tiqr-develop-20150507103441Z-f07a3c01ea97a3fea88d77c4978aad6daeb28cd5.tar.bz2
      component_name: tiqr
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"


- name: Install Stepup-Keyserver
  hosts: stepup-keyserver
  sudo: True
  tags: oath-service-php

  roles:
        - stepup-keyserver

  vars:
      component_tarball_name: oath-service-php-develop-20150603123314Z-b927846e2310c7883baa841940bb8a9e75f16230.tar.bz2
      component_name: keyserver
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\\\1') }}"
