---

# This "deploy.yml" playbook is used to deploy the components, it requires the infrastructure deployed with "site.yml"
#
# Use the provided deploy.sh script to deploy a single component
#
# To deploy all components in one go, set "tarball_location" to the directory where the tarballls to be deployed are stored. E.g.
# ansible-playbook .../Stepup-Deploy/deploy.yml -i .../inventory -e tarball_location=`pwd`


- hosts: all
  run_once: true

  tasks:
  - name: Require Ansible 2
    assert:
      that: ansible_version.major == 2


- name: Intall Stepup-Gateway
  hosts: stepup-gateway
  become: True
  tags: stepup-gateway

  roles:
      - stepup-gateway

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-Gateway-2.2.0-20161018092553Z-bc6bbf8e2006d15cbe883d8045724cdb1166e759.tar.bz2"
      component_name: gateway
      component_vhost_name: "{{ gateway_vhost_name }}"
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\1') }}"


- name: Install Stepup-middleware
  hosts: stepup-middleware
  become: True
  tags: stepup-middleware

  roles:
        - stepup-middleware

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-Middleware-2.0.2-20160810101855Z-d8d88d778ea30379b606cbca58d9634ff0541b42.tar.bz2"
      component_name: middleware
      component_vhost_name: "{{ middleware_vhost_name }}"
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\1') }}"


- name: Install Stepup-SelfService
  hosts: stepup-selfservice
  become: True
  tags: stepup-selfservice

  roles:
        - stepup-selfservice

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-SelfService-2.2.0-20161018092804Z-8792083b95fe2e073318ba68e4f92329249673ad.tar.bz2"
      component_name: selfservice
      component_vhost_name: "{{ selfservice_vhost_name }}"
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\1') }}"


- name: Install Stepup-RA
  hosts: stepup-ra
  become: True
  tags: stepup-ra

  roles:
        - stepup-ra

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-RA-2.2.0-20161018093029Z-8dc3497ba0fc70701abeb1c890b6956a80ca24e9.tar.bz2"
      component_name: ra
      component_vhost_name: "{{ ra_vhost_name }}"
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\1') }}"


- name: Install Stepup-tiqr IDP
  hosts: stepup-tiqr
  become: True
  tags: stepup-tiqr

  roles:
        - stepup-tiqr

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-tiqr-1.1.3-20160708120851Z-e5d8000f03e81f780cab77a439a86db6e0b37ad8.tar.bz2"
      component_name: tiqr
      component_vhost_name: "{{ tiqr_vhost_name }}"
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\1') }}"


- name: Install Stepup-Keyserver
  hosts: stepup-keyserver
  become: True
  tags: oath-service-php

  roles:
        - stepup-keyserver

  vars:
      component_tarball_name: "{{ tarball_location }}/oath-service-php-1.0.1-20150723081351Z-56c990e62b4ba64ac755ca99093c9e8fce3e8fe9.tar.bz2"
      component_name: keyserver
      component_vhost_name: "{{ keyserver_vhost_name }}"
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\1') }}"


- name: Install Stepup-Azure-MFA IDP
  hosts: stepup-azuremfa
  become: True
  tags: stepup-azure-mfa

  roles:
        - stepup-azure-mfa

  vars:
      component_tarball_name: "{{ tarball_location }}/Stepup-Azure-MFA-0.2.6-20191223115638Z-74c9b883a2f21aa1702eb01eaa978fd934221a1c.tar.bz2"
      component_name: azuremfa
      component_vhost_name: "{{ azuremfa_vhost_name }}"
      component_dir_name: "/opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\\.tar\\.bz2$', '\\1') }}"
      stable_nonce: "{{ component_tarball_name | basename | regex_replace('^.*-(.{8}).{32}\\.tar\\.bz2$', '\\1') }}"
