- name: Intall Stepup-Gateway
  hosts: app
  sudo: True
  tags: gateway

  vars:
      component_tarball_name: Stepup-Gateway-develop-20141202081514Z-e8ef9e8b0a34180c14fefbe3a847edc47c3ef3be.tar.bz2
      component_name: gateway
      component_dir_name: /opt/stepup/{{ component_tarball_name | basename | regex_replace('^(.*)\.tar\.bz2$', '\\1') }}

  roles:
      - stepup-gateway
