---
# Push middleware config
# This playbook writes the middleware configuration to each targeted app host and then executes the
# /root/middleware-config.sh to push the config to the middleware
# "run_once: True" is used to execute the push once instead of on each trageted host

- name: Push middleware config
  hosts: stepup-middleware
  sudo: True

  tasks:
  - name: Write middleware config and whitelist to /root/
    template: src={{ inventory_dir }}/templates/middleware/{{ item }}.j2 dest=/root/{{ item }} group=root owner=root mode="400" backup=yes
    with_items:
    - middleware-config.json
    - middleware-whitelist.json


  # The /root/middleware-* scripts were written by middleware deploy
  - name: Push middleware configuration
    command: /root/02-middleware-config.sh
    run_once: True

  - name: Push middleware whitelist
    command: /root/04-middleware-whitelist.sh
    run_once: True

