---
# Ansible playbook for setting up the step-up infrastructure
# Run:
# cd Stepup-Deploy
# ansible-playbook -i inventory environment/<env>/inventory site.yml

- name: Configuration for all nodes
  hosts: all
  sudo: True
  tags: common

  roles:
  - common


- name: Setup management server
  hosts: manage
  sudo: True
  tags: manage

  roles:
  - manage


- name: Setup mariadb database cluster
  hosts: dbcluster
  sudo: True
  tags: db
  serial: 1

  roles:
  - db


- name: Setup elasticseach cluster
  hosts: es
  sudo: True
  tags: es
  serial: 1

  roles:
    - es


- name: Setup application servers
  hosts: app
  sudo: True
  tags: app

  roles:
  - app


- name: Setup proxy on application servers
  hosts: proxy
  sudo: True
  tags: proxy

  roles:
  - proxy


- name: Dev tools
  hosts: dev
  sudo: True
  tags: dev

  roles:
  - dev

- name: Setup loadbalancer servers
  hosts: lb
  sudo: True
  tags: lb

  roles:
  - lb


