- hosts: app

  vars:
     arg:
       state: directory
       mode: 700
       owner: vagrant
       group: vagrant

  tasks:
  - name: Test
    debug:
      msg: "{{ ss_remote_vetting_idps[item].certificate }}"
    with_items: "{{ ss_remote_vetting_idps.keys() }}"
