---
# Drop middleware and gateway databases

- name: Drop middleware and gateway databases
  hosts: all

  tasks:
  - name: Keydir
    debug: msg="vault_keydir = {{ vault_keydir }}"

  - name: Encrypted
    debug: msg="Encrypted mariadb_root_password = {{ mariadb_root_password }}"

  - name: Test vault
    debug: msg="Decrypted mariadb_root_password = {{ mariadb_root_password | vault(vault_keydir) }}"