# Add config for a HTTPS proxy on the app server
# Assumes nginx has been installed previously

# Create SSL config for proxy to local vhost
- include: proxy.yml
  vhost_name: "{{ gateway_vhost_name }}"
  component_name: gateway
  proxy_certificate: "{{ proxy_gateway_certificate }}"
  proxy_key: "{{ proxy_gateway_key }}"

- include: proxy.yml
  vhost_name: "{{ selfservice_vhost_name }}"
  component_name: selfservice
  proxy_certificate: "{{ proxy_selfservice_certificate }}"
  proxy_key: "{{ proxy_selfservice_key }}"

- include: proxy.yml
  vhost_name: "{{ ra_vhost_name }}"
  component_name: ra
  proxy_certificate: "{{ proxy_ra_certificate }}"
  proxy_key: "{{ proxy_ra_key }}"

# TODO: adapt so that TLS terminates on key server instead of proxy/LB
- include: proxy.yml
  vhost_name: "{{ keyserver_vhost_name }}"
  component_name: keyserver
  proxy_certificate: "{{ proxy_keyserver_certificate }}"
  proxy_key: "{{ proxy_keyserver_key }}"