# Assumes ngix has been installed previously

# Create SSL config for proxy to vhost
- include: proxy.yml
  vhost_name: gateway
  proxy_certificate: "{{ proxy_gateway_certificate }}"
  proxy_key: "{{ proxy_gateway_key }}"

- include: proxy.yml
  vhost_name: selfservice
  proxy_certificate: "{{ proxy_selfservice_certificate }}"
  proxy_key: "{{ proxy_selfservice_key }}"

- include: proxy.yml
  vhost_name: ra
  proxy_certificate: "{{ proxy_ra_certificate }}"
  proxy_key: "{{ proxy_ra_key }}"
