# Add config for a HTTPS proxy on the app server
# Assumes nginx has been installed previously

- name: Put /etc/nginx/dhparams.pem
  copy: src={{ inventory_dir }}/files/dhparams.pem dest=/etc/nginx/dhparams.pem

# Create SSL config for proxy to local vhost
- include: proxy.yml
  vars:
    vhost_name: "{{ gateway_vhost_name }}"
    component_name: gateway
    proxy_certificate: "{{ proxy_gateway_certificate }}"
    proxy_key: "{{ proxy_gateway_key }}"
  when: "inventory_hostname in groups['stepup-gateway']"

- include: proxy.yml
  vars:
    vhost_name: "{{ selfservice_vhost_name }}"
    component_name: selfservice
    proxy_certificate: "{{ proxy_selfservice_certificate }}"
    proxy_key: "{{ proxy_selfservice_key }}"
  when: "inventory_hostname in groups['stepup-selfservice']"

- include: proxy.yml
  vars:
    vhost_name: "{{ ra_vhost_name }}"
    component_name: ra
    proxy_certificate: "{{ proxy_ra_certificate }}"
    proxy_key: "{{ proxy_ra_key }}"
  when: "inventory_hostname in groups['stepup-ra']"

- include: proxy.yml
  vars:
    vhost_name: "{{ tiqr_vhost_name }}"
    component_name: tiqr
    proxy_certificate: "{{ proxy_tiqr_certificate }}"
    proxy_key: "{{ proxy_tiqr_key }}"
  when: "inventory_hostname in groups['stepup-tiqr'] | default([])"

- include: proxy.yml
  vars:
    vhost_name: "{{ webauthn_vhost_name }}"
    component_name: webauthn
    proxy_certificate: "{{ proxy_webauthn_certificate }}"
    proxy_key: "{{ proxy_webauthn_key }}"
  when: "inventory_hostname in groups['stepup-webauthn'] | default([])"

# TODO: adapt so that TLS terminates on key server instead of proxy/LB
- include: proxy.yml
  vars:
    vhost_name: "{{ keyserver_vhost_name }}"
    component_name: keyserver
    proxy_certificate: "{{ proxy_keyserver_certificate }}"
    proxy_key: "{{ proxy_keyserver_key }}"
  when: "inventory_hostname in groups['stepup-keyserver'] | default([])"


- include: proxy.yml
  vars:
    vhost_name: "{{ demo_gssp_vhost_name }}"
    component_name: demo-gssp
    proxy_certificate: "{{ proxy_demo_gssp_certificate }}"
    proxy_key: "{{ proxy_demo_gssp_key }}"
  when: "inventory_hostname in groups['stepup-demo-gssp'] | default([])"

- include: proxy.yml
  vars:
    vhost_name: "{{ demo_gssp_2_vhost_name }}"
    component_name: demo-gssp-2
    proxy_certificate: "{{ proxy_demo_gssp_2_certificate }}"
    proxy_key: "{{ proxy_demo_gssp_2_key }}"
  when: "inventory_hostname in groups['stepup-demo-gssp-2'] | default([])"