# Copyright 2014 SURFnet bv
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |v|
        v.memory = 1024
    end

    config.vm.box = "jayunit100/centos7"

    config.vm.network :private_network, ip: "10.0.0.100"

    if which('ansible-playbook')
        config.vm.provision "ansible" do |ansible|
            ansible.playbook = "../provisioning/ansible/suaas.yml"
            ansible.inventory_path = "../provisioning/ansible/inventories/development"
            ansible.limit = "suaas"
        end
    else
        config.vm.provision :shell, inline: "env PLAYBOOK=../provisioning/ansible/suaas.yml ../provisioning/ansible/windows.sh"
    end

    config.vm.synced_folder "./", "/vagrant", type: "nfs"

    # Mount shared folders after provisioning
    # https://github.com/mitchellh/vagrant/issues/936#issuecomment-7179034
    config.vm.synced_folder "../../Stepup-Middleware",  "/var/www/mw-dev.stepup.coin.surf.net"
    config.vm.synced_folder "../../Stepup-Gateway",     "/var/www/gw-dev.stepup.coin.surf.net"
    config.vm.synced_folder "../../Stepup-SelfService", "/var/www/ss-dev.stepup.coin.surf.net"
    config.vm.synced_folder "../../Stepup-RA",          "/var/www/ra-dev.stepup.coin.surf.net"
    config.vm.provision :shell, inline: "mount -t vboxsf -o uid=middleware,gid=middleware   var_www_mw-dev.stepup.coin.surf.net /var/www/mw-dev.stepup.coin.surf.net"
    config.vm.provision :shell, inline: "mount -t vboxsf -o uid=gateway,gid=gateway         var_www_gw-dev.stepup.coin.surf.net /var/www/gw-dev.stepup.coin.surf.net"
    config.vm.provision :shell, inline: "mount -t vboxsf -o uid=selfservice,gid=selfservice var_www_ss-dev.stepup.coin.surf.net /var/www/ss-dev.stepup.coin.surf.net"
    config.vm.provision :shell, inline: "mount -t vboxsf -o uid=ra,gid=ra                   var_www_ra-dev.stepup.coin.surf.net /var/www/ra-dev.stepup.coin.surf.net"
end

# Check to determine whether we're on a windows or linux/os-x host,
# later on we use this to launch ansible in the supported way
# source: https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each { |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable? exe
        }
    end
    return nil
end
