- name: Setup mysql directory for mysqlping
  file: state=directory dest=/usr/lib/ocf/resource.d/mysql/
  when: pacemaker_mysqlping

- name: Setup mysqlping binary
  copy: src=mysqlping mode=0755 dest=/usr/lib/ocf/resource.d/mysql/mysqlping
  when: pacemaker_mysqlping

- name: Configure mysqlping resource
  command: pcs resource create {{ mysqlping_config.name }} ocf:mysql:mysqlping dampen={{ mysqlping_config.dampen }} host_list={{ mysqlping_config.host_list }} multiplier={{ mysqlping_config.multiplier }} op monitor interval={{ mysqlping_config.monitor_interval }} timeout={{ mysqlping_config.monitor_timeout }}
  when: mysqlping_config.name not in resource_status.stdout and pacemaker_mysqlping

- name: Clone mysqlping resource
  command: pcs resource clone {{ mysqlping_config.name }} {{ mysqlping_config.name}}-clone globally-unique=false
  when: mysqlping_config.name not in resource_status.stdout and pacemaker_mysqlping

- name: Configure mysqlping locations
  command: pcs constraint location add {{ mysqlping_config.name }}-{{ item.split('.')[0] }} {{ mysqlping_config.name}}-clone {{ item }} 100
  with_items: groups.dbcluster
  when: mysqlping_config.name not in resource_status.stdout and pacemaker_mysqlping

- name: Configure mysqlping IP preferred location
  command: pcs constraint location add {{ item }}-pref-location {{ mysqlping_ip_resource }} {{ item }} 100
  with_items: groups.dbcluster
  when: mysqlping_config.name not in resource_status.stdout and pacemaker_mysqlping and item == groups.dbcluster[0]

- name: Configure mysqlping IP alternative locations
  command: pcs constraint location add {{ item }}-alt-location {{ mysqlping_ip_resource }} {{ item }} 10
  with_items: groups.dbcluster
  when: mysqlping_config.name not in resource_status.stdout and pacemaker_mysqlping and item != groups.dbcluster[0]

- name: Configure mysqlping rule
  command: pcs constraint location {{ mysqlping_ip_resource }} rule id=mysqlping score=333 defined mysqlping
