---

- name: Restart elasticsearch
  service: name=elasticsearch state=restarted

# Wait until port 9200 and 9300 accept connections
# Start polling after <delay> seconds, try for max <timeout> seconds
- name: Wait for elasticsearch
  wait_for: delay=0 port={{ item }} timeout=60 state=started
  with_items:
  - 9200
  - 9300
