# Infra suff for RA

- name: Put parameters, samlstepupproviders(_parameters) and global_view_parameters YAML config
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ component_config_dir_name }}/{{ item }}.{{ component_config_yaml_extension }}"
    mode: "{{ component_mode_640 }}"
    group: "{{ component_group }}"
  with_items:
  - parameters
  - samlstepupproviders
  - samlstepupproviders_parameters
  - global_view_parameters


# Deploy does change file rights in config, so run deploy first, then write files
- name: Deploy Symfony component
  include_role:
    name: deploy
    tasks_from: deploy


#symfony 3 locations
- name: Put images from <env>/files/stepup-app into web/images
  copy: src={{ item }} dest={{ component_dir_name }}/web/images mode=444 group={{ component_group }}
  with_fileglob:
  - "{{inventory_dir }}/files/stepup-app/images/*"
  when: deploy_symfony_3

- name: Put images from <env>/files/stepup-app/second-factor into web/images/second-factor
  copy: src={{ item }} dest={{ component_dir_name }}/web/images/second-factor mode={{ component_mode_444 }} group={{ component_group }}
  with_fileglob:
  - "{{inventory_dir }}/files/stepup-app/images/second-factor/*"
  when: deploy_symfony_3

#symfony 4 locations
- name: Put images from <env>/files/stepup-app into public/images
  copy: src={{ item }} dest={{ component_dir_name }}/public/images mode=444 group={{ component_group }}
  with_fileglob:
  - "{{inventory_dir }}/files/stepup-app/images/*"
  when: deploy_symfony_4

- name: Put images from <env>/files/stepup-app/second-factor into public/images/second-factor
  copy: src={{ item }} dest={{ component_dir_name }}/public/images/second-factor mode={{ component_mode_444 }} group={{ component_group }}
  with_fileglob:
  - "{{inventory_dir }}/files/stepup-app/images/second-factor/*"
  when: deploy_symfony_4

# SAML SP signing certificate for authentication to the normal authentication (i.e. /authentication/metadata) IdP enspoint
# on the Stepup-Gateway
- name: Write SAML SP private key
  copy: content="{{ ra_saml_sp_privatekey | vault(vault_keydir) }}" dest={{ component_config_file_dir_name }}/sp.key owner={{ component_owner }} mode={{ component_mode_400 }}

- name: Write SAML SP certificate
  copy: content="{{ ra_saml_sp_publickey }}" dest={{ component_config_file_dir_name }}/sp.crt group={{ component_group }} mode={{ component_mode_640 }}

# SAML SP signing certificate for authentication to the GSSP IdP proxy enspoint(s)
# on the Stepup-Gateway
- name: Write GSSP SP private key
  copy: content="{{ ra_gssp_sp_privatekey | vault(vault_keydir) }}" dest={{ component_config_file_dir_name }}/sp_gssp.key owner={{ component_owner }} mode={{ component_mode_400 }}

- name: Write GSSP SP certificate
  copy: content="{{ ra_gssp_sp_publickey }}" dest={{ component_config_file_dir_name }}/sp_gssp.crt group={{ component_group }} mode={{ component_mode_640 }}


- name: Activate selfservice component
  include_role:
    name: deploy
    tasks_from: activate
