# Infra suff for RA

- name: Put parameters.yml, samlstepupproviders(_parameters).yml and global_view_parameters.yml
  template: src={{ item }}.j2 dest={{ component_dir_name }}/app/config/{{ item }} mode={{ component_mode_640 }} group={{ component_group }}
  with_items:
  - parameters.yml
  - samlstepupproviders.yml
  - samlstepupproviders_parameters.yml
  - global_view_parameters.yml


# Deploy does change file rights in config, so run deploy first, then write files
- name: Deploy Symfony component
  include_role:
    name: deploy
    tasks_from: deploy


- name: Put images from <env>/files/stepup-app into web/images
  copy: src={{ item }} dest={{ component_dir_name }}/web/images mode=444 group={{ component_group }}
  with_fileglob:
  - "{{inventory_dir }}/files/stepup-app/images/*"

- name: Put images from <env>/files/stepup-app/second-factor into web/images/second-factor
  copy: src={{ item }} dest={{ component_dir_name }}/web/images/second-factor mode={{ component_mode_444 }} group={{ component_group }}
  with_fileglob:
  - "{{inventory_dir }}/files/stepup-app/images/second-factor/*"


# SAML SP signing certificate for authentication to the normal authentication (i.e. /authentication/metadata) IdP enspoint
# on the Stepup-Gateway
- name: Write SAML SP private key
  copy: content="{{ ra_saml_sp_privatekey | vault(vault_keydir)  }}" dest={{ component_dir_name }}/app/config/sp.key owner={{ component_owner }} mode={{ component_mode_400 }}

- name: Write SAML SP certificate
  copy: content="{{ ra_saml_sp_publickey }}" dest={{ component_dir_name }}/app/config/sp.crt group={{ component_group }} mode={{ component_mode_640 }}

# SAML SP signing certificate for authentication to the GSSP IdP proxy enspoint(s)
# on the Stepup-Gateway
- name: Write GSSP SP private key
  copy: content="{{ ra_gssp_sp_privatekey | vault(vault_keydir)  }}" dest={{ component_dir_name }}/app/config/sp_gssp.key owner={{ component_owner }} mode={{ component_mode_400 }}

- name: Write GSSP SP certificate
  copy: content="{{ ra_gssp_sp_publickey }}" dest={{ component_dir_name }}/app/config/sp_gssp.crt group={{ component_group }} mode={{ component_mode_640 }}


- name: Activate selfservice component
  include_role:
    name: deploy
    tasks_from: activate