# Infra suff for middleware

- name: Get active component
  shell: readlink /opt/www/{{ component_name }}.{{ app_domain }}
  ignore_errors: true
  register: active_component

- debug:
    msg: |
       Currently installed component: {{ active_component.stdout }}
       Component to be installed    : {{ component_dir_name }}

- name: Check whether component is installed
  fail: msg="Component already active"
  when: ( 0 ) and ( component_dir_name != active_component.stdout)


- name: Create stepup directory
  file: path={{ component_dir_name }} state=directory

- name: Untar component
  unarchive: copy=yes src={{ component_tarball_name }} dest={{ component_dir_name }}

- name: Put parameters.yml
  template: src=parameters.yml.j2 dest={{ component_dir_name }}/app/config/parameters.yml


- name: Dump Assetic Assets
  shell: php {{ component_dir_name }}/app/console assetic:dump --env=prod --no-debug

- name: Clear cache
  shell: php {{ component_dir_name }}/app/console cache:clear --env=prod --no-debug

- name: Grant app write access to cache and log dirs
  file: path={{item}} owner=gateway recurse=yes
  with_items:
  - "{{ component_dir_name }}/app/cache"
  - "{{ component_dir_name }}/app/logs"


- name: Activate component
  file: src={{ component_dir_name }} dest=/opt/www/{{ component_name }}.{{ app_domain }} state=link