# Infra suff for RA

- name: Put parameters.yml, samlstepupproviders(_parameters).yml and global_view_parameters.yml
  template: src={{ item }}.j2 dest={{ component_dir_name }}/app/config/{{ item }} mode={{ component_mode_640 }} group={{ component_group }}
  with_items:
  - parameters.yml
  - samlstepupproviders.yml
  - samlstepupproviders_parameters.yml
  - global_view_parameters.yml

- name: Put images from <env>/files/stepup-app into web/images
  copy: src={{ item }} dest={{ component_dir_name }}/web/images mode=444 group={{ component_group }}
  with_fileglob:
  - "{{inventory_dir }}/files/stepup-app/images/*"

- name: assets:install
  command: php app/console assets:install --symlink --env=prod {{ debug_flag }}
  args:
      chdir: "{{ component_dir_name }}"

- name: mopa:bootstrap:symlink:less
  command: php app/console mopa:bootstrap:symlink:less --env=prod {{ debug_flag }}
  args:
      chdir: "{{ component_dir_name }}"

- name: Dump Assetic Assets
  command: php app/console assetic:dump --env=prod {{ debug_flag }}
  args:
      chdir: "{{ component_dir_name }}"

- name: Clear and warmup cache
  command: php app/console cache:clear --env=prod {{ debug_flag }}
  args:
      chdir: "{{ component_dir_name }}"
  when: not (develop | default(false))

- name: Restrict app dir to the application
  file: path={{item}} group={{ component_group }} mode="o=" recurse=yes
  with_items:
  - "{{ component_dir_name }}/app"
  when: not (develop | default(false))

- name: Grant app write access to cache and log dirs
  file: path={{item}} group={{ component_group }} mode={{ component_mode_770 }} recurse=yes
  with_items:
  - "{{ component_dir_name }}/app/cache"
  - "{{ component_dir_name }}/app/logs"
  when: not (develop | default(false))

# SAML SP signing certificate for authentication to the normal authentication (i.e. /authentication/metadata) IdP enspoint
# on the Stepup-Gateway
- name: Write SAML SP private key
  copy: content="{{ ra_saml_sp_privatekey | vault(vault_keydir)  }}" dest={{ component_dir_name }}/app/config/sp.key owner={{ component_owner }} mode={{ component_mode_400 }}

- name: Write SAML SP certificate
  copy: content="{{ ra_saml_sp_publickey }}" dest={{ component_dir_name }}/app/config/sp.crt group={{ component_group }} mode={{ component_mode_640 }}

# SAML SP signing certificate for authentication to the GSSP IdP proxy enspoint(s)
# on the Stepup-Gateway
- name: Write GSSP SP private key
  copy: content="{{ ra_gssp_sp_privatekey | vault(vault_keydir)  }}" dest={{ component_dir_name }}/app/config/sp_gssp.key owner={{ component_owner }} mode={{ component_mode_400 }}

- name: Write GSSP SP certificate
  copy: content="{{ ra_gssp_sp_publickey }}" dest={{ component_dir_name }}/app/config/sp_gssp.crt group={{ component_group }} mode={{ component_mode_640 }}


- name: Set stepup directory rights
  file: path={{ component_dir_name }} state=directory group={{ component_group }} mode={{ component_mode_755 }}

- name: Activate component
  file: src={{ component_dir_name }} dest=/opt/www/{{ ra_vhost_name }} state=link
