#!/bin/bash

sleep 3

IP_ADDRESS=$(ifdata -pa eth0)

GRAYLOG2_URL="http://admin:yourpassword@${IP_ADDRESS}:12900"

GRAYLOG2_INPUT_GELF_TCP='
{
      "global": "true",
      "title": "Gelf TCP",
      "configuration": {
        "port": 12201,
        "bind_address": "0.0.0.0"
      },
      "creator_user_id": "admin",
      "type": "org.graylog2.inputs.gelf.tcp.GELFTCPInput"
}'

GRAYLOG2_INPUT_GELF_UDP='
{
      "global": "true",
      "title": "Gelf UDP",
      "configuration": {
        "port": 12201,
        "bind_address": "0.0.0.0"
      },
      "creator_user_id": "admin",
      "type": "org.graylog2.inputs.gelf.udp.GELFUDPInput"
}'


INPUTS=$(curl -X GET -H "Content-Type: application/json" ${GRAYLOG2_URL}/system/inputs 2>/dev/null)

if [ $(echo $INPUTS | grep -c "GELF TCP") != "1" ]; then
	curl -X POST -H "Content-Type: application/json" -d "${GRAYLOG2_INPUT_GELF_TCP}" ${GRAYLOG2_URL}/system/inputs > /dev/null
fi

if [ $(echo $INPUTS | grep -c "GELF UDP") != "1" ]; then
	curl -X POST -H "Content-Type: application/json" -d "${GRAYLOG2_INPUT_GELF_UDP}" ${GRAYLOG2_URL}/system/inputs > /dev/null
fi

exit 0
