
# Create user & group for FPM pool
- name: Add group {{ vhost_name }}
  group: name={{ vhost_name }} state=present

- name: Add user {{ vhost_name }}
  user: name={{ vhost_name }} group={{ vhost_name }} createhome=no state=present


- name: Create directory for vhosts to store PHP sessions
  file: path=/var/lib/php/session/{{ vhost_name }} state=directory owner={{ vhost_name }} group=root mode=770

- name: Create /opt/www/
  file: path=/opt/www/ state=directory

# Create a default app
# When no app is installed yet in the webdirectory then a link to the default app is created
- name: Create default app directory for {{ vhost_name }}.{{ app_domain }}
  file: path=/opt/default/{{ vhost_name }}.{{ app_domain }}/web/ state=directory

- name: Create default /opt/default/{{ vhost_name }}.{{ app_domain }}/web/app.php
  template: src='httpd-index.php.j2' dest='/opt/default/{{ vhost_name }}.{{ app_domain }}/web/app.php'


- name: Install default app when no app is installed (yet)
  file: src=/opt/default/{{ vhost_name }}.{{ app_domain }} dest=/opt/www/{{ vhost_name }}.{{ app_domain }} state=link force=no


# Put httpd vhost config
- name: Put httpd vhost config for {{ vhost_name }}
  action: template src='nginx-vhost.conf.j2' dest='/etc/nginx/conf.d/{{ vhost_name }}.{{ app_domain }}.conf'
  notify:
    - restart nginx


# Put fpm config
- name: php-fpm config
  template: src='php-fpm-pool.conf.j2' dest='/etc/php-fpm.d/{{ vhost_name }}.{{ app_domain }}.conf'
  notify:
    - restart php-fpm
