
# Create user & group for FPM pool
- name: Add group {{ vhost_name }}
  group: name={{ vhost_name }} state=present

- name: Add user {{ vhost_name }}
  user: name={{ vhost_name }} group={{ vhost_name }} createhome=no state=present


# Create web directory
- name: Create app directory for {{ vhost_name }} in /opt/stepup
  file: path=/opt/stepup/{{ vhost_name }}.{{ app_domain }} state=directory

# Create index.php if not exists
- name: Create /opt/stepup/{{ vhost_name }}.{{ app_domain }}/index.php if not exists
  template: src='httpd-index.php.j2' dest='/opt/stepup/{{ vhost_name }}.{{ app_domain }}/index.php' force=no


# Put httpd vhost config
- name: Put httpd vhost config for {{ vhost_name }}
  action: template src='nginx-vhost.conf.j2' dest='/etc/nginx/conf.d/{{ vhost_name }}.{{ app_domain }}.conf'
  notify:
    - restart nginx


# Put fpm config
- name: php-fpm config
  action: template src='php-fpm-pool.conf.j2' dest='/etc/php-fpm.d/{{ vhost_name }}.{{ app_domain }}.conf'
  notify:
    - restart php-fpm
