- name: Create Gateway database
  mysql_db: name={{ database_gateway_name }} state=present login_user=root login_password={{ mariadb_root_password | vault(vault_keydir) }}

- name: Create gateway user
  mysql_user:
    name={{ database_gateway_user }}
    host={{ hostvars[item].host_ipv4 }}
    password={{ database_gateway_password | vault(vault_keydir) }}
    priv={{ database_gateway_name }}.*:SELECT,EXECUTE
    login_user=root
    login_password={{ mariadb_root_password | vault(vault_keydir) }}
  with_items: "{{ groups['app'] }}"
