- name: Create keyserver database
  mysql_db: name={{ database_keyserver_name }} state=present login_user=root login_password={{ mariadb_root_password | vault(vault_keydir) }}

- name: Create keyserver user
  mysql_user:
    name={{ database_keyserver_user }}
    host={{ hostvars[item].host_ipv4 }}
    password={{ database_keyserver_password | vault(vault_keydir) }}
    priv={{ database_keyserver_name }}.*:SELECT,INSERT,DELETE,EXECUTE,UPDATE
    login_user=root
    login_password={{ mariadb_root_password | vault(vault_keydir) }}
  with_items: "{{ groups['app'] }}"
