- name: Create tiqr database
  mysql_db: name={{ database_tiqr_name }} state=present login_user=root login_password={{ mariadb_root_password | vault(vault_keydir) }}

- name: Create tiqr user
  mysql_user:
    name={{ database_tiqr_user }}
    host={{ hostvars[item].host_ipv4 }}
    password={{ database_tiqr_password | vault(vault_keydir) }}
    priv={{ database_tiqr_name }}.*:SELECT,INSERT,DELETE,EXECUTE,UPDATE
    login_user=root
    login_password={{ mariadb_root_password | vault(vault_keydir) }}
  with_items: "{{ groups['app'] }}"
