# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2)  do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "StepUp-log-Server"
  config.vm.network :private_network, ip: "10.10.0.101"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  $script = <<SCRIPT
    apt-get update
    echo 'Going to download Graylog...'
    curl -S -s -L -O https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb
    dpkg -i graylog_latest.deb
    rm graylog_latest.deb
    graylog-ctl set-external-ip http://127.0.0.1:12900
    graylog-ctl set-admin-username admin
    graylog-ctl set-admin-password password
    graylog-ctl set-timezone "Europe/Amsterdam"
    graylog-ctl reconfigure
SCRIPT

  config.vm.provision "shell", inline: $script
end
