---

# MariaDB service from RedHat is called "mariadb", MariaDB service from MariaDB is called "mysql"
   - name: restart mariadb
     script: mysql_reboot_cluster.sh "{{ mariadb_root_password | vault }}"