- name: Set /etc/hostname to {{ inventory_hostname }}
  template: src='hostname.j2' dest='/etc/hostname'

- name: Write /etc/hosts with {{ inventory_hostname }}
  template: src='hosts.j2' dest='/etc/hosts'


# Directory for keeping misc ansible files
- name: Create managed files dir
  file: name={{ managed_file_dir }} state=directory


- name: Set SELinux policy to targeted & permissive
  selinux: policy=targeted state=permissive


- name: Set timezone
  file: src=/usr/share/zoneinfo/{{ timezone }}  dest=/etc/localtime state=link force=yes


# Extra Packages for Enterprise Linux
# https://fedoraproject.org/wiki/EPEL
- name: Enable EPEL repo
  yum: name=epel-release.noarch state=present
  tags: epel


# Firewall changed from ip(6)tables start/stop in CentOS6 to firewalld in CentOS7
# ip(6)tables can still be installed using iptables-services
# First disable firewalld service
- name: "Disable firewalld"
  service: name=firewalld enabled=no state=stopped


- name: Install ntp, iptables, ip6tables, rsyslog
  yum: name={{item}} state=present
  with_items:
  - ntp
  - iptables-services
  - rsyslog # Is the default syslog for RH / CentOS
  - rsyslog-relp # For using RELP with rsyslog


- name: Put iptables
  template: src={{ inventory_dir }}/templates/common/iptables.j2 dest='/etc/sysconfig/iptables'
  notify:
  - restart iptables

- name: Put ip6tables
  template: src={{ inventory_dir }}/templates/common/ip6tables.j2 dest='/etc/sysconfig/ip6tables'
  notify:
  - restart ip6tables

- name: Put ntp.conf
  template: src={{ inventory_dir }}/templates/common/ntp.conf.j2 dest='/etc/ntp.conf'
  notify:
  - restart ntpd


- name: Start and enable services ntpd, iptables, iptables6
  service: name={{item}} state=started enabled=true
  with_items:
  - ntpd
  - iptables
  - ip6tables

# Create directory for rsyslog message buffer
- name: Create rsyslog dir
  file: name=/var/lib/rsyslog state=directory


# Setup rsyslog
- name: Put rsyslog config
  template: src='rsyslog/rsyslog.conf.j2' dest='/etc/rsyslog.conf'
  notify: restart rsyslog
