
- name: Set SELinux policy to targeted & permissive
  selinux: policy=targeted state=permissive

- name: Enable EPEL repo
  yum: name=epel-release.noarch state=present
  tags: epel


- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
  tags: ntp

