- name: Set /etc/hostname to {{ inventory_hostname }}
  template: src='hostname.j2' dest='/etc/hostname'

- name: Set SELinux policy to targeted & permissive
  selinux: policy=targeted state=permissive


# Set timezone
- name: Check current timezone
  shell: awk -F\" '{ print $2}' /etc/sysconfig/clock
  register: current_zone
  changed_when: False

- name: Set UTC timezone
  file: src=/usr/share/zoneinfo/{{ timezone }}  dest=/etc/localtime state=link force=yes
  when: current_zone.stdout != '{{ timezone }}'


# Extra Packages for Enterprise Linux
# https://fedoraproject.org/wiki/EPEL
- name: Enable EPEL repo
  yum: name=epel-release.noarch state=present
  tags: epel


- name: Install ntp, iptables, ip6tables, rsyslog
  yum: name={{item}} state=present
  with_items:
  - ntp
  - iptables
  - rsyslog


- name: Put iptables
  template: src='iptables.j2' dest='/etc/sysconfig/iptables'
  notify:
  - restart iptables

- name: Put ip6tables
  template: src='ip6tables.j2' dest='/etc/sysconfig/ip6tables'
  notify:
  - restart ip6tables


- name: Start services ntpd, iptables, iptables6
  service: name={{item}} state=started enabled=true
  with_items:
  - ntpd
  - iptables
  - ip6tables


# Directory for keeping misc ansible files
- name: Create managed files dir
  file: name={{ managed_file_dir }} state=directory


# Setup rsyslog to graylog
- name: Add rsyslog config to forward logs to graylog2
  template: src='90-graylog2.conf.j2' dest='/etc/rsyslog.d/90-graylog2.conf'
  notify: restart rsyslog