# Install demo gssp component

- name: Exit if not develop
  fail: msg="You should never install the demo gssp in production"
  when: not (develop | default(false))

# nodejs 12 and yarn were installed by the dev role using nvm
- name: Run yarn encore dev using nodejs 12
  shell:
    cmd: source /root/.bashrc && nvm use 12 && yarn && yarn encore dev
    chdir: "{{ component_dir_name }}"

- name: Copy .env file
  copy: remote_src=True src={{ component_dir_name }}/.env.ci dest={{ component_dir_name }}/.env

- name: Put parameters.yml
  template: src={{ item }}.j2 dest={{ component_dir_name }}/config/packages/{{ item }} mode=666
  with_items:
    - parameters.yaml

- name: Create app_dev.php
  file:
    src: "{{ component_dir_name }}/public/index.php"
    dest: "{{ component_dir_name }}/public/app_dev.php"
    state: link

# This is the certificate of the SP that the Demo GSSP trusts for validating SAML AuthnRequests form the Stepup-Gateway
- name: Write Demo GSSP SP certificate
  copy: content="{{ gateway_gssp_sp_publickey }}" dest={{ component_dir_name }}/config/sp.pem group={{ component_group }} mode={{ component_mode_640 }}


# These are the certificate and key that the Demo GSSP uses for signing SAML Responses for the Stepup-Gateway
- name: Write Demo GSSP idp certificate
  copy: content="{{ demo_gssp_idp_publickey }}" dest={{ component_dir_name }}/config/idp.pem group={{ component_group }} mode={{ component_mode_640 }}

- name: Write Demo GSSP idp private key
  copy: content="{{ demo_gssp_idp_privatekey | vault(vault_keydir) }}" dest={{ component_dir_name }}/config/idp.key owner={{ component_owner }} mode={{ component_mode_400 }}


# Finish
- name: Activate component
  file: src={{ component_dir_name }} dest=/opt/www/{{ component_vhost_name }} state=link
