# This task will set up test databases in the development environment.
# The permissions for the test tables are lowered to easily set up  schemes

# Add test databases for middleware to allow functional testing in development environment
- name: Create middleware test database
  mysql_db: name={{ database_middleware_name }}_test state=present login_user=root login_password={{ mariadb_root_password | vault(vault_keydir) }}

- name: Set permissions for middleware test database
  mysql_user:
    name: "{{ database_middleware_user }}"
    host: "%"
    password: "{{ database_middleware_password | vault(vault_keydir) }}"
    priv: "{{ database_middleware_name }}_test.*:ALL\ PRIVILEGES,GRANT"
    append_privs: yes
    login_user: root
    login_password: "{{ mariadb_root_password | vault(vault_keydir) }}"

- name: Set permission for middleware test database for deploy user with ALL access to middleware and gateway database
  mysql_user:
    name: "{{ database_middleware_deploy_user }}"
    host: "%"
    password: "{{ database_middleware_deploy_password | vault(vault_keydir) }}"
    priv: "{{ database_gateway_name }}_test.*:ALL\ PRIVILEGES,GRANT/{{ database_middleware_name }}_test.*:ALL\ PRIVILEGES"
    append_privs: yes
    login_host: "127.0.0.1"
    login_user: "root"
    login_password: "{{ mariadb_root_password | vault(vault_keydir) }}"

# Add test databases for gateway to allow functional testing in development environment
- name: Create gateway test database
  mysql_db: name={{ database_gateway_name }}_test state=present login_user=root login_password={{ mariadb_root_password | vault(vault_keydir) }}

- name: Set permissions for gateway test database for gateway user
  mysql_user:
    name: "{{ database_gateway_user }}"
    host: "%"
    password: "{{ database_gateway_password | vault(vault_keydir) }}"
    priv: "{{ database_gateway_name }}_test.*:ALL\ PRIVILEGES,GRANT"
    append_privs: yes
    login_user: root
    login_password: "{{ mariadb_root_password | vault(vault_keydir) }}"

- name: Set permissions for gateway test database for middleware user
  mysql_user:
    name: "{{ database_middleware_user }}"
    host: "%"
    password: "{{ database_middleware_password | vault(vault_keydir) }}"
    priv: "{{ database_gateway_name }}_test.*:ALL\ PRIVILEGES,GRANT"
    append_privs: yes
    login_user: root
    login_password: "{{ mariadb_root_password | vault(vault_keydir) }}"

# Add test databases for tiqr to allow functional testing in development environment
- name: Create tiqr test database
  mysql_db: name={{ database_tiqr_name }}_test state=present login_user=root login_password={{ mariadb_root_password | vault(vault_keydir) }}

- name: Set permissions for gateway test database
  mysql_user:
    name: "{{ database_tiqr_user }}"
    host: "%"
    password: "{{ database_tiqr_password | vault(vault_keydir) }}"
    priv: "{{ database_tiqr_name }}_test.*:ALL\ PRIVILEGES,GRANT"
    append_privs: yes
    login_host: "127.0.0.1"
    login_user: root
    login_password: "{{ mariadb_root_password | vault(vault_keydir) }}"
