---
- name: Install NodeJS
  yum: name=nodejs state=present

- name: Install xdebug
  yum: name=php-pecl-xdebug state=present

- name: Install NPM
  yum: name=npm state=present

- name: Install LESS compiler
  npm: name=less global=yes state=present