---
#- name: Install NodeJS
#  yum: name=nodejs state=present

#- name: Install xdebug
#  yum: name=php-pecl-xdebug state=present

#- name: Install NPM
#  yum: name=npm state=present

#- name: Install LESS compiler
#  npm: name=less global=yes state=present

- name: Download /usr/local/bin/composer from https://getcomposer.org/composer.phar
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=555 owner=root group=root



