---
- name: restart nginx
  service: name=nginx state=restarted enabled=true

- name: restart php-fpm
  service: name=php-fpm enabled=yes state=restarted

- name: Reload firewall
  command: firewall-cmd --reload
